### ISSUE TITLE
Add 1K resistor in line with GPIO 19/26

### ISSUE THREAD

**Issue by sharrington93** [BuckeyeCurrent/Mid-MCN-Breakout#1]

**Comment by Victorb101** [comment]
@aaronbeekay @sharrington93 Is this still a valid issue?  This change was never implemented.  The coolant flow sensor (and all other GPIO sensors) have large pullup resistors to 3V3 and are selectively pulled to ground by the sensor.  

What was the reason for this issue?  Does it need to be implemented now?

**Comment by aaronbeekay** [comment]
@sharrington93 - I don't remember why we decided to do this originally. Do you?

**Comment by sharrington93** [comment]
@aaronbeekay @Victorb101 I only remember this is back from when we were testing the filtering I believe. I don't remember the exact reasoning either now.

**Comment by aaronbeekay** [comment]
OK... I guess I'll close this out then.
